"""Add logistics to booking

Revision ID: bc42ade18971
Revises: 
Create Date: 2026-04-25 12:07:25.366618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc42ade18971'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('renter_name', sa.String(length=255), nullable=True))
    op.add_column('bookings', sa.Column('renter_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'renter_phone')
    op.drop_column('bookings', 'renter_name')
    op.drop_column('bookings', 'delivery_address')
    # ### end Alembic commands ###
